Unsupervised learning is a branch of machine learning that tries to find hidden structures within unlabeled
data and derive insights from it. Clustering, data dimensionality-reduction techniques, noise reduction,
segmentation, anomaly detection, fraud detection, and other rich methods rely on unsupervised learning to
drive analytics. **Today, with so much data around us, it is impossible to label all data for supervised learning.
This makes unsupervised learning all the more important.** Restricted Boltzmann machines and auto-
encoders are unsupervised methods that are based on artificial neural networks. 


# Boltzman Distribution

Restricted Boltzmann machines are **energy models based on the Boltzmann Distribution Law** of classical
physics, where the state of particles of any system is represented by their generalized coordinates and
velocities. 

These generalized coordinates and velocities form the phase space of the particles, and the
particles can be in any location in the phase space with specific energy and probability. Let’s consider a
classical system that contains N gas molecules and let the generalized position and velocity of any particle
be represented by r and v respectively. The location of the particle in the phase space can be
represented by (r, v). Every such possible value of (r, v) that the particle can take is called a configuration of
the particle. Further, all the N particles are identical in the sense that they are equally likely to take up any
state. Given such a system at thermodynamic temperature T, the probability of any such configuration is
given as follows:

$$\large P ( r , v ) \propto e ^ { - \frac { E ( r , v ) } { K T } }$$

E(r, v) is the energy of any particle at configuration (r, v), and K is the Boltzmann Constant. Hence,
we see that the probability of any configuration in the phase space is proportional to the exponential of
the negative of the energy divided by the product of the Boltzmann Constant and the thermodynamic
temperature. To convert the relationship into an equality, the probability needs to be normalized by the sum
of the probabilities of all the possible configurations. If there are M possible phase-space configurations for
the particles, then the probability of any generalized configuration (r, v) can be expressed as:


$$P ( r , v ) = \frac { e ^ { -  \large\frac { E ( r , v ) } { K T } } } { Z }$$

where Z is the partition function given by:

$$Z = \sum _ { i = 1 } ^ { M } e ^  { - \large\frac { E \left( ( r , v ) _ { i } \right) } { K T } }$$

M denotes all the unique combinations of r and v possible, which have been denoted by (r, v)i in the preceding equation. If r can take up n distinct
coordinate values whereas v can take up m distinct velocity values, then the total number of possible
configurations M = n*m . In such cases, the partition function can also be expressed as follows:

$$Z = \sum _ { j = 1 } ^ { m } \sum _ { i = 1 } ^ { n } e ^ { - \large\frac { E \left( r _ { i } , v _ { j } \right) } { K T } }$$

# Bayesian Inference

**Likelihood** is the probability of the observed data given the parameters that generate the underlying data.
Let’s suppose we observe n observations x1, x2,..... xn and assume that the observations are independent and
identically normally distributed with mean μ and variance σ2.

The likelihood function in this case would be as follows:  

$$P (Data/Model parameters) = P \left( x _ { 1 } , x _ { 2 } , \ldots . x _ { n } / \mu , \sigma ^ { 2 } \right)$$

Since the observations are independent, we can factorize the likelihood as follows:

$$P (Data/Model parameters) = \prod _ { i = 1 } ^ { n } P \left( x _ { i } / \mu , \sigma ^ { 2 } \right)$$

Each of the:

$$x _ { i } \sim \operatorname { Normal } \left( \mu , \sigma ^ { 2 } \right)$$

hence the likelihood can be further expanded as follows:

$$P(Data/Modelparameters) = \prod _ { i = 1 } ^ { n } \frac { 1 } { \sqrt { 2 \pi } \sigma } e ^ { \large\frac { - \left( x _ { i } - \mu \right) ^ { 2 } } { 2 \sigma ^ { 2 } } }.$$

Whenever I get data I build a model by defining a likelihood function over the
data conditioned on the model parameters and then try to maximize that likelihood function. Likelihood is
nothing but the probability of the seen or observed data given the model parameters:

$$ Likelihood = P (Data/Model)$$
    
To get the model defined by its parameters we maximize the likelihood of the seen data:

$$Model = Argmax \hspace{0.4cm} P (Data/Model)$$

    
**Since we are only trying to fit a model based on the observed data, there is a high chance of overfitting
and not generalizing to new data if we go for simple likelihood maximization.**
If the data size is huge the seen data is likely to represent the population well and so maximizing the
likelihood may suffice. On the other hand, if the seen data is small, there is a high chance that it might not
represent the overall population well, and thus the model based on likelihood would not generalize well
to new data. In that case, having a certain prior belief over the model and constraining the likelihood by
that prior belief would lead to better results. Let’s say that **the prior belief is in the form of our knowing the
uncertainty over the model parameters in the form of a probability distribution; i.e., P(Model) is known.** We
can in that case update our likelihood by the prior information to get a distribution over the model given the
data. As per Bayes’ Theorem of Conditional Probability

$$P(\text {Model} / \text { Data } ) = \frac { P ( \text { Data/Model } ) P ( \text {Model} ) } { P ( \text { Data } )}$$


**P(Model/Data) is called the posterior distribution** and is generally more informative since it combines
one’s prior knowledge about the data or model. Since this probability of data is independent of the model,
the posterior is directly proportional to the product of the likelihood and the prior:  
 

$$P (\text {Model} / \text { Data } ) \propto P ( Data/Model) P ( Model)$$



# tf.ceil vs tf.floor

In [23]:
import tensorflow as tf
 
t1 = tf.constant([[1.5, 3.5, 4.5], [4, 4, 4], [3, 3, 3]])
 
ceil_tensor = tf.ceil(t1)
floor_tensor = tf.floor(t1)
exp_tensor = tf.exp(t1)
pow_tensor = tf.pow(t1, 2)
log_tensor = tf.log(t1)
 
sess = tf.Session()
 
print("\n----------- (Ceil) ----------------\n")
print(sess.run(ceil_tensor))
 
print("\n----------- (Floor) ----------------\n")
print(sess.run(floor_tensor))


----------- (Ceil) ----------------

[[2. 4. 5.]
 [4. 4. 4.]
 [3. 3. 3.]]

----------- (Floor) ----------------

[[1. 3. 4.]
 [4. 4. 4.]
 [3. 3. 3.]]


# Restricted Boltzmann Machines

Restricted Boltzmann machines (RBMs) belong to the unsupervised class of machine-learning algorithms
that utilize the Boltzmann Equation of Probability Distribution. It is a two-layer
restricted Boltzmann machine architecture that has a hidden layer and a visible layer. There are weight
connections between all the hidden and visible layers’ units. However, there are no hidden-to-hidden or
visible-to-visible unit connections.

The term restricted in RBM refers to this constraint on the network.
The hidden units of an RBM are conditionally independent from one another given the set of visible units.

In terms of probabilistic graphic models, restricted Boltzmann
machines can be defined as undirected probabilistic graphic models containing a visible layer and a single
hidden layer. 

The energy of the joint probability distribution’s having hidden state h and visible state v is given by

$$P ( v , h ) = \frac { e ^ {\large- E ( h , v ) } } { Z }$$

where E(v, h) is the energy of the joint configuration (v, h) and Z is the normalizing factor, commonly
known as the partition function. This probability is based on the Boltzmann distribution and assumes the
Boltzmann Constant and thermal temperature as 1.

$$Z = \sum _ { v } \sum _ { h } e ^ { -\large E ( v , h ) }$$

<font color='green'>**RBM are probabilistic. As opposed to assigning discrete values the model assigns probabilities. At each point in time the RBM is in a certain state. The state refers to the values of neurons in the visible and hidden layers v and h. The probability that a certain state of v and h can be observed is given by the joint distribution above.** </font> 



The energy E(v, h) of the joint configuration (v, h) is given by

$$E ( v , h ) = - \sum _ { i = 1 } ^ { m } b _ { i } v _ { i } - \sum _ { j = 1 } ^ { n } c _ { j } h _ { j } - \sum _ { j = 1 } ^ { n } \sum _ { i = 1 } ^ { m } v _ { i } w _ { i j } h _ { j }$$


As it can be noticed **the value of the energy function depends on the configurations of visible/input states, hidden states, weights and biases. The training of RBM consists in finding of parameters for given input values so that the energy reaches a minimum**.



In [24]:
##Import the Required libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [25]:
## Read the MNIST files
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)

## Set up the parameters for training
n_visible = 784
n_hidden = 500
display_step = 1
num_epochs = 200
batch_size = 256
lr = tf.constant(0.001, tf.float32)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [26]:
## Define the tensorflow variables for weights and biases as well as placeholder for input
x = tf.placeholder(tf.float32, [None, n_visible], name="x")
W = tf.Variable(tf.random_normal([n_visible, n_hidden], 0.01), name="W")
b_h = tf.Variable(tf.zeros([1, n_hidden], tf.float32, name="b_h"))
b_v = tf.Variable(tf.zeros([1, n_visible], tf.float32, name="b_v"))
print('x:',x,'\nW:',W,'\nb_h:',b_h,'\nb_v',b_v)

x: Tensor("x_1:0", shape=(?, 784), dtype=float32) 
W: <tf.Variable 'W_1:0' shape=(784, 500) dtype=float32_ref> 
b_h: <tf.Variable 'Variable_2:0' shape=(1, 500) dtype=float32_ref> 
b_v <tf.Variable 'Variable_3:0' shape=(1, 784) dtype=float32_ref>


In [27]:
## Converts the probability into discrete binary states; i.e., 0 and 1
def sample(probs):
    #tf.random_uniform(shape,minval=0, maxval=None,dtype=tf.float32,seed=None,name=None)
    #tf.floor() 
    a = tf.floor(probs + tf.random_uniform(tf.shape(probs), 0, 1))
    return a

## Gibbs sampling step
def gibbs_step(x_k):
    h_k = sample(tf.sigmoid(tf.matmul(x_k, W) + b_h))
    x_k = sample(tf.sigmoid(tf.matmul(h_k, tf.transpose(W)) + b_v))
    return x_k

## Run multiple Gibbs sampling steps starting from an initial point
def gibbs_sample(k,x_k):
    for i in range(k):
        x_out = gibbs_step(x_k)   
       # Returns the Gibbs sample after k iterations
    return x_out

In [28]:
# Constrastive Divergence algorithm
# 1. Through Gibbs sampling locate a new visible state x_sample based on the current visible state x
# 2. Based on the new x sample a new h as h_sample
x_s = gibbs_sample(2,x)
print ('x_s',x_s)
h_s = sample(tf.sigmoid(tf.matmul(x_s, W) + b_h))
# Sample hidden states based given visible states
h = sample(tf.sigmoid(tf.matmul(x, W) + b_h))
# Sample visible states based given hidden states
x_ = sample(tf.sigmoid(tf.matmul(h, tf.transpose(W)) + b_v))


x_s Tensor("Floor_43:0", shape=(?, 784), dtype=float32)


As in Physics we assign a probability to observe a state of v and h, that depends on the overall energy of the model. Unfortunately it is very difficult to calculate the joint probability due to the huge number of possible combination of v and h in the partition function Z. Much easier is the calculation of the conditional probabilities of state h given the state v and conditional probabilities of state v given the state h:

$$p ( \mathbf { h } | \mathbf { v } ) = \prod _ { i } p \left( h _ { i } | \mathbf { v } \right)$$
$$p ( \mathbf { v } | \mathbf { h } ) = \prod _ { i } p \left( v _ { i } | \mathbf { h } \right)$$


It should be noticed beforehand (before demonstrating this fact on practical example) that each neuron in a RBM can only exist in a binary state of 0 or 1. The most interesting factor is the probability that a hidden or visible layer neuron is in the state 1 — hence activated. Given an input vector v the probability for a single hidden neuron j being activated is:
$$p \left( h _ { j } = 1 | \mathbf { v } \right) = \frac { 1 } { 1 + e ^ { \left( - \left( b _ { j } + W _ { j } v _ { i } \right) \right) } } = \sigma \left( b _ { j } + \sum _ { i } v _ { i } w _ { i j } \right)$$

$$p \left( v _ { i } = 1 | \mathbf { h } \right) = \frac { 1 } { 1 + e ^ { \left( - \left( a _ { i } + W _ { i } h _ { j } \right) \right) } } = \sigma \left( a _ { i } + \sum _ { j } h _ { j } w _ { i j } \right)$$

Here is σ the Sigmoid function.


**Computing the Gradients**

The values obtained in the previous step can be used to compute the gradient matrix and the gradient vectors
The update of the weight matrix happens during the Contrastive Divergence step.   

$$\triangle W = \mathbf { v } _ { 0 } \otimes p \left( \mathbf { h } _ { 0 } | \mathbf { v } _ { 0 } \right) - \mathbf { v } _ { k } \otimes p \left( \mathbf { h } _ { k } | \mathbf { v } _ { k } \right)$$

$$\triangle b = p \left( \mathbf { h } _ { 0 } | \mathbf { v } _ { 0 } \right) - p \left( \mathbf { h } _ { k } | \mathbf { v } _ { k } \right)$$

$$\Delta a = \mathbf { v } _ { 0 } - \mathbf { v } _ { k }$$

Using the update matrix the new weights can be calculated with gradient ascent, given by:

$$W _ { n e w } = W _ { o l d } + \triangle W$$  
$$a _ { n e w } = a _ { o l d } + \Delta a$$  
$$b _ { n e w } = b _ { o l d } + \triangle b$$  

In [29]:
# The weight updated based on gradient descent
size_batch = tf.cast(tf.shape(x)[0], tf.float32)
W_add = tf.multiply(lr/size_batch, tf.subtract(tf.matmul(tf.transpose(x), h), tf.matmul(tf.transpose(x_s), h_s)))

bv_add = tf.multiply(lr/size_batch, tf.reduce_sum(tf.subtract(x, x_s), 0, True))
bh_add = tf.multiply(lr/size_batch, tf.reduce_sum(tf.subtract(h, h_s), 0, True))

updt = [W.assign_add(W_add), b_v.assign_add(bv_add), b_h.assign_add(bh_add)]

# Training a Restricted Boltzmann Machine

We need to train the Boltzmann machine in order to derive the model parameters b, c, W, where b and c are
the bias vectors at the visible and hidden units respectively and W is the weight-connections matrix between
the visible and hidden layers.  

For ease of reference, the model parameters can be collectively referred to as:

$$\theta = [ b ; c ; W ]$$


**Gibbs sampler**

Gibbs sampler is a Markov chain Monte Carlo (MCMC) algorithm for obtaining a sequence of observations which are approximated from a specified multivariate probability distribution, when direct sampling is difficult. This sequence can be used to approximate the joint distribution (e.g., to generate a histogram of the distribution.

Suppose p(x, y) is a p.d.f. or p.m.f. that is difficult to sample from directly.

1. Suppose, though, that we can easily sample from the conditional distributions p(x|y) and p(y|x).
2. The Gibbs sampler proceeds as follows:
    1. set x and y to some initial starting values
    2. then sample x|y, then sample y|x, then x|y, and so on.

<img src="files/Img/4.png" style="width: 500px;">







This procedure defines a sequence of pairs of random variables
(X0, Y0),(X1, Y1),(X2, Y2),(X3, Y3), . . .

(X0, Y0),(X1, Y1),(X2, Y2),(X3, Y3), . . .
satisfies the property of being a Markov chain.
The conditional distribution of (Xi
, Yi) given all of the previous
pairs depends only on (Xi−1, Yi−1)


In [ ]:
# TensorFlow graph execution
with tf.Session() as sess:
    # Initialize the variables of the Model
    init = tf.global_variables_initializer()
    sess.run(init)
  
    total_batch = int(mnist.train.num_examples/batch_size)
    # Start the training
    for epoch in range(num_epochs):
        # Loop over all batches
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            # Run the weight update
            batch_xs = (batch_xs > 0)*1
            _ = sess.run([updt], feed_dict={x:batch_xs})
        # Display the running step
        #if epoch % display_step == 0:
            #print("Epoch:", '%04d' % (epoch+1))
     
    print("RBM training Completed !")
    ## Generate hidden structure for 1st 20 images in test MNIST
    out = sess.run(h,feed_dict={x:(mnist.test.images[:20]> 0)*1})
    label = mnist.test.labels[:20]
    ## Take the hidden representation of any of the test images; i.e., the 3rd record
    ## The output level of the 3rd record should match the image generated
    plt.figure(1)
    for k in range(20):
        plt.subplot(4, 5, k+1)
        image = (mnist.test.images[k]> 0)*1
        image = np.reshape(image,(28,28))
        plt.imshow(image,cmap='gray')

    plt.figure(2)
    for k in range(20):
        plt.subplot(4, 5, k+1)
        image = sess.run(x_,feed_dict={h:np.reshape(out[k],(-1,n_hidden))})
        image = np.reshape(image,(28,28))
        plt.imshow(image,cmap='gray')
        print(np.argmax(label[k]))
    sess.close()


##  Deep belief networks (DBNs)

Deep belief networks are based on the restricted Boltzmann machine but, unlike an RBN, a DBN has
multiple hidden layers. The weights in each hidden layer K are trained by keeping all the weights in the prior
( K - 1 ) layers constant. The activities of the hidden units in the ( K -1) layer are taken as input for the
Kth layer. At any particular time during training two layers are involved in learning the weight connections
between them. The learning algorithm is the same as that of restricted Boltzmann machines

The DBN
learning algorithm is used to learn the initial weights of a deep network being used for supervised learning
so that the network has a good set of initial weights to start with. Once the pre-training is done for the deep
belief network, we can add an output layer to the DBN based on the supervised problem at hand

<font color='green'> Let’s say we want to train a model to perform classification on the MNIST dataset. In that case, we would have to
append a ten-class SoftMax layer. We can then fine-tune the model by using backpropagation of error. Since
the model already has an initial set of weights from unsupervised DBN learning, the model would have a
good chance of converging faster when backpropagation is invoked.<font>

We now look at an implementation of DBN pre-training of weights followed by the training of a
classification network by appending the output layer to the hidden layer of the RBM. We
implemented RBM, wherein we learned the weights of the visible-to-hidden connections, assuming all the
units are sigmoid. To that RBM we are going to stack the output layer of ten classes for the MNIST dataset
and train the classification model using the weights from the visible-to-hidden units learned as the initial
weights for the classification network. Of course, we would have a new set of weights corresponding to the
connection of the hidden layer to the output layer.

In [ ]:
##Import the Required libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
## Read the MNIST files
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
## Set up the parameters for training
n_visible = 784
n_hidden = 500
display_step = 1
num_epochs = 200
batch_size = 256
lr = tf.constant(0.001, tf.float32)
learning_rate_train = tf.constant(0.01, tf.float32)
n_classes = 10
training_iters = 200
## Define the tensorflow variables for weights and biases as well as placeholder forx = tf.placeholder(tf.float32, [None, n_visible], name="x")
y = tf.placeholder(tf.float32, [None,10], name="y")
W = tf.Variable(tf.random_normal([n_visible, n_hidden], 0.01), name="W")
b_h = tf.Variable(tf.zeros([1, n_hidden], tf.float32, name="b_h"))
b_v = tf.Variable(tf.zeros([1, n_visible], tf.float32, name="b_v"))
W_f = tf.Variable(tf.random_normal([n_hidden,n_classes], 0.01), name="W_f")
b_f = tf.Variable(tf.zeros([1, n_classes], tf.float32, name="b_f"))
## Converts the probability into discrete binary states i.e. 0 and 1
def sample(probs):


**References:**
1. http://deeplearning.net/tutorial/rbm.html
2. http://web.science.mq.edu.au/~mjohnson/papers/Johnson12IntroRBMtalk.pdf
3. https://arxiv.org/pdf/1806.07066.pdf
4. https://www.cs.toronto.edu/~hinton/absps/guideTR.pdf
5. https://www.slideshare.net/sogo1127/learning-rbmrestricted-boltzmann-machine-in-practice
6. https://towardsdatascience.com/deep-learning-meets-physics-restricted-boltzmann-machines-part-i-6df5c4918c15
7. http://www2.stat.duke.edu/~rcs46/modern_bayes17/lecturesModernBayes17/lecture-7/07-gibbs.pdf
8. http://www.uta.fi/sis/tie/neuro/index/Neurocomputing7.pdf
9. https://www.cse.unsw.edu.au/~cs9444/17s2/lect/1page/11_Boltzmann.pdf
10. http://www.cs.toronto.edu/~rgrosse/courses/csc321_2017/slides/lec19.pdf

